[[pages]]
path = "pages/home.py"
name = "Welcome to ğŸ—£ï¸2ğŸŒ"
icon = ""


[[pages]]
path = "pages/events.py"
name = "Plans"
icon = "ğŸ“…"
url_path="events"

[[pages]]
path = "pages/jobs.py"
name = "Jobs"
icon = "ğŸ‘·"
url_path = "Jobs" # You can override the default url path for a page